[colors.bright]
black = "#686868"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[colors.normal]
black = "#01060E"
blue = "#53BDFA"
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#EA6C73"
white = "#C7C7C7"
yellow = "#F9AF4F"

[colors.primary]
background = "#000000"
foreground = "#B3B1AD"

[font]
size = 11.0

[font.bold]
family = "Monaspace Xenon"
style = "Bold"

[font.bold_italic]
family = "Monaspace Xenon"
style = "Bold Italic"

[font.italic]
family = "Monaspace Xenon"
style = "Italic"

[font.normal]
family = "Monaspace Xenon"
style = "Bold"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[window]
opacity = 0.85
