import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Ayu-Dark.toml"
]

[colors.primary]
background = "#000000"
foreground = "#B3B1AD"

[font]
size = 11

[font.bold]
family = "Comic mono"
style = "Bold"

[font.bold_italic]
family = "Comic mono"
style = "Bold Italic"

[font.italic]
family = "Comic mono"
style = "Italic"

[font.normal]
family = "Comic mono"
style = "Bold"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50_000

[window]
opacity = 0.9
